### ISSUE TITLE
High surprising scores per cuisine when using fam_cat <preprocessor.py>

### ISSUE THREAD

**Issue by otayeby** [Kazjon/GloVex#5]
When running the <preprocessor.py> using the following parameters:
`"/PQE/Omar/RecipeDataSummer2017/recipe_cuisine_all_tagged_multi_plural_modern_w_Ingredients_freq_0" --dataset "recipes" --overwrite_preprocessing --overwrite_model --epochs 15 --use_famcats`

Enclosed please find the results of the surprising combinations for each cuisine. [fam_cat-top_n combos multi_plural modern.txt](https://github.com/Kazjon/GloVex/files/1644983/fam_cat-top_n.combos.multi_plural.modern.txt)

What I noticed is that the modern cuisine has better combinations and surprising scores, which might be linked back to the fact that the modern cuisine has large number of training examples rather than the other cuisines.

Also, I noticed that some combinations have observation cooccurrence equals to zero. Which follows a question, isn't it supposed to be at least one in order to be considered a combination? I am not sure of this part.

**Comment by Kazjon** [comment]
I've fixed the zero cooccurrence part of this in the latest comment in feature_apply_recipe, it was a logic error in print_top_n_surps.

**Comment by Kazjon** [comment]
OK, I think I've now fixed the other issues with this -- I'm getting much more sensible surprise readings on both personalised and oracle versions.
