### ISSUE TITLE
The <evaluate.py> script is printing the least surprising (high scores) documents/recipes instead of the most surprising

### ISSUE THREAD

**Issue by otayeby** [Kazjon/GloVex#6]
The <evaluate.py> script is printing the least surprising combinations per recipe as shown in this output: [eval-multi-plural-modern.txt](https://github.com/Kazjon/GloVex/files/1644990/eval-multi-plural-modern.txt) using the following script parameters: `"/PQE/Omar/RecipeDataSummer2017/recipe_cuisine_all_tagged_multi_plural_modern_w_Ingredients_freq_0" --dataset "recipes" --epoch 15 --overwrite_preprocessing --overwrite_model`

A log function is needed to have an inverse effect.

Also, this issue might be related to issue #5

**Comment by Kazjon** [comment]
I've fixed this in my own repo, not fully tested it yet so I haven't pushed.

**Comment by Kazjon** [comment]
OK, I think I've finally gotten to the bottom of this one.  It was being confused by the reporting of probabilities vs log probabilities, and now that's fixed it's clearer what's happening.  There's actually nothing in evaluate.py that trains the glovex model, and unless you set the parameters to exactly the same as a model that's already been trained and saved using the preprocessor, then it will happily report surprise values from an *untrained* model -- i.e. one initialised effectively randomly.  

I'm going to change the evaluate scripts to train glovex if it can't read in an existing one.

**Comment by Kazjon** [comment]
OK, I've now figured out the weird "salt & sugar" combinations.  When training the "modern" glove model the error at some point turns into NaN, which causes the surprise predictions to be NaN, which makes them get replaced at some point by a very large number.  Not quite sure what the cause of those NaNs is, but it's definitely what's causing those combinations.  When I run it with the first5000 dataset, there's no "modern", so no problem.  

Other cuisines are training fine, but the evaluate scripts are returning either the highest or some kind of average, and that's being thrown off by the huge number from the modern famcat.

I'm going to try to fix this tomorrow, I think.  I'm currently pushing a solution to the "untrained models" problem, and I'll tackle the "modern NaN" thing next.

**Comment by Kazjon** [comment]
I think I got this one.
