### ISSUE TITLE
Wrong indexing of the dictionary surps in the document_surprise function of the <evaluate_personalized.py>

### ISSUE THREAD

**Issue by otayeby** [Kazjon/GloVex#7]
The line in document_surprise of the `evaluate_personalized.py`:
Produces the error message below, because the indexing of the dictionary is assuming a list instead. The surps variable in [surps.txt](https://github.com/Kazjon/GloVex/files/1648309/surps.txt) shows the user familiarity scores (the list 'user') and surps dictionary for that user.
`return np.percentile([x[2] for x in surps], 100 - percentile) #note that percentile calculates the highest.`

Error message:
```
Traceback (most recent call last):
  File "/PQE/Omar/GloVex/evaluate_personalised.py", line 245, in <module>
    dataset_surps = eval_personalised_dataset_surprise(models, reader, user)
  File "/PQE/Omar/GloVex/evaluate_personalised.py", line 23, in eval_personalised_dataset_surprise
    dataset_surps.append({"id": id, "raw":raw_doc, "surprises":surps, "surprise": document_surprise(surps)})
  File "/PQE/Omar/GloVex/evaluate_personalised.py", line 33, in document_surprise
    return np.percentile([x[2] for x in surps], 100 - percentile) #note that percentile calculates the highest.
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by Kazjon** [comment]
On this now.

**Comment by Kazjon** [comment]
Definitely seeing very different results between evalaute_personalised and evaluate even when using the "single category" data.

**Comment by Kazjon** [comment]
After teh recent merge/patches/etc, evaluate_personalised and the preprocessor on the same data (the first 5000 recipes with "all" as the famcat for all of them) still produces different data.

**Comment by Kazjon** [comment]
OK, fixed this, I think.  Still seeing occasional "NaN" values in the modern category, but I'm going to close this and merge my fixes branch back in.  Any future errors we'll make a new issue for!
